Try #2 Sprint 9
shumitum/java-filmorate pull request #7
Opened 2023-03-18 00:20 UTC by shumitum

2023-03-18 22:23 UTC, TarasovSam requested changes
Вадим, спасибо за внесение корректировок. Оставил несколько комментариев на некоторые исправления.
Общий вопрос, зачем ты сделал новый пул, а не продолжил в старом? Это весьма не удобно, т.к. мои комментарии не перенеслись. Продолжай работать (вносить изменения) в старом пуле. Или были какие-то проблемы с этим?
Задание отправлю на доработку, чтобы убедиться, что все нормально с продолжением работы в том же пуле.
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку.

2023-03-18 22:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmManager.getListOfFilms();
А почему здесь не проводишь логирование?
Для пользователя тоже самое.

2023-03-18 22:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Согласно ТЗ для Film:
- название не может быть пустым (тут все понятно);
- максимальная длина описания — 200 символов (тут же описание может быть пустым, т.е. его просто не написали);
- дата релиза — не раньше 28 декабря 1895 года (здесь тоже дата релиза может отсутствовать);
- продолжительность фильма должна быть положительной (и здесь тоже).
Поэтому поправь свои аннотации (некоторые лишние).

2023-03-18 22:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NonNull
Если в патерне у тебя не предусмотрена проверка на пустой логин, то я рекомендую заменить @NonNull на @NotBlank.

2023-03-18 22:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NonNull
По ТЗ для User:
дата рождения не может быть в будущем (т.е. может быть не заполненной по сути).

2023-03-18 22:23 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Вот все же нужна предварительная проверка на null, чтобы не поймать NPЕ.

2023-03-18 22:36 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmManager.getListOfFilms();
По ТЗ логирование необходимо для операций, которые изменяют сущности — добавляют и обновляют их.  Метод getListOfFilms() не делает ни того, ни другого.

2023-03-19 00:21 UTC, shumitum commented
Замечания исправил.
По поводу отсутствия логирования в методах getListOfFilms() и getListOfUsers().
По ТЗ логирование необходимо для операций, которые изменяют сущности — добавляют и обновляют их. Метод getListOfFilms() не делает ни того, ни другого.

2023-03-19 19:36 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmManager.getListOfFilms();
Так-то да, но согласись, что логично логировать и эти действия, раз мы логируем не только ошибки (что встречается чаще), но и удачные попытки создания, изменения.
Смотри конечно сам, будет пища для размышлений:)

2023-03-19 19:42 UTC, TarasovSam reviewed
Вадим, спасибо за твои ответы и за внесение корректировок, плюс радует, что готов разбираться в вопросе. Оставил комментарий на твой комментарий (тавтология) по поводу getAll и еще один на счет id.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-19 19:42 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
В прошлый раз сосредоточился на других полях и не обратил внимание. А для id не нужна никакая аннотация? 
И для пользователя тоже.

2023-03-19 20:14 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int id;
Думаю что нет, id генерируется на серверной стороне, с фронта это поле должно приходить пустое, а если в этом поле что-нибудь будет его заменит сгенерированный соответствующим менеджером id

2023-03-19 22:24 UTC, merged