Try #1 Sprint 10
shumitum/java-filmorate pull request #8
Opened 2023-03-24 10:17 UTC by shumitum

2023-03-24 21:16 UTC, TarasovSam requested changes
Вадим, привет!
Проверил твое задание, спасибо за работу. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-03-24 21:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
У тебя для id в коде в некоторых местах не хватает проверки на null для этого поля. Это можно решить, прописав аннотацию)
Тоже самое и для Film. 
И почему здесь ты поменял int на Long, а для фильма нет?

Плюс предложение к рассмотрению - ввести поле рейтинг фильма)

2023-03-24 21:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public interface FilmService {
Так, а вот тут ты довольно интересно решил сделать, хоть и не совсем так, как нужно)
Сервис - не интерфейс, это класс, в котором прописана реализация всех методов, которые вызываются в контроллере.
Тоже самое и для пользователя.

2023-03-24 21:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
А вот Storage - интерфейс, в котором объявляются методы CRUD. Т.е. как минимум добавь сюда getFilm, а если будет желание, то и deleteFilm.

Методы для FilmStorage и UserStorage идентичны, поэтому можно их выделить в интерфейс с использованием дженериков.
Тоже самое можно сделать и для InMemoryStorage, но там несколько замороченнее)
Это (вторая часть комментария) рекомендация к рассмотрению.

2023-03-24 21:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NoSuchElementException("Фильма с ID=" + film.getId() + " не существует");
При неудачных попытках тоже можно проводить логирование, для полноты картины в логах, так сказать.
Для пользователя тоже самое.

2023-03-24 21:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private int filmId;
Для поля userId проводишь инициализацию, а тут нет. Почему?

2023-03-26 00:33 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NoSuchElementException("Фильма с ID=" + film.getId() + " не существует");
Логирование исключений теперь в ErrorHandler

2023-03-26 00:34 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +            throw new NoSuchElementException("Фильма с ID=" + film.getId() + " не существует");
Логирование исключений теперь в ErrorHandler

2023-03-26 00:45 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Long id;
Валидация ID на null все ломает, ID генерируется на серверной стороне, при создании пользователя с фронта это поле должно приходить пустое, а даже если в этом поле что-нибудь будет его заменит сгенерированный id, в тестах постмана  на создание пользователя приходящий json не содержит поля id, а методе на обновление пользователя, проверяется наличие пользователя по ID в мапе пользователей, если null или несуществующий ID генерируют исключение.

2023-03-26 20:51 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private int filmId;
userId  - Long ссылочный тип данных, если ничего не присвоить там будет null, со всеми вытекающими из этого проблемами.
filmId - int примитив, инициализируется нулем.

2023-03-26 20:54 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
В ТЗ не просили, а для отлавливания и исправления багов вполне хватало тестов постмана

2023-03-27 00:55 UTC, shumitum commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Я решил что на данном этапе взаимодействовать с хранилищем через интерфейс проще и понятней, чем прокидывать данные через сервис.

2023-03-27 18:17 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Да, в ТЗ этого не было. Это дополнение для улучшения приложения в разрезе сохранения (логирования) всех действий. Т.е. в логе будет полное прослеживание того, что делалось - какие запросы отправлены, какие ответы пришли, какие ошибки появились.

2023-03-27 18:21 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Может и проще, но точно не понятнее в том смысле, что это отличается от общепринятых правил, что есть контроллер, сервис и в эндпоинте идет вызов соответствующего метода сервиса.
Еще бывает такая структура: контроллер -> интерфейс сервис -> сервис с реализацией.

2023-03-27 18:35 UTC, TarasovSam reviewed
Вадим, привет!
Проверил твое задание, спасибо за работу и за то, что дорабатываешь код (в том числе и сверх нормы так сказать). Оставил еще пару комментариев, посмотри их, пожалуйста.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-27 18:35 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateService.java
> -            log.warn("Некорректна дата релиза фильма: {}", film);
В принципе тут и в других местах логирование можно не убирать. Да, у тебя логирование проходит в ErrorHandler, но они не взаимозаменяют, а дополняют. Т.е. в логе будет больше информации (более подробной и адресной), а не общей и обезличенной.

2023-03-27 18:35 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +                .sorted(Comparator.comparingInt(f -> f.getLikedUserIds().size() * -1))
Так у тебя же есть поле рейтинг, почему не используешь его?)

2023-04-11 22:22 UTC, merged