sprint 11 try #1
shumitum/java-filmorate pull request #9
Opened 2023-04-20 02:45 UTC by shumitum

2023-04-20 14:10 UTC, TarasovSam requested changes
Вадим, привет!
Проверил твое задание, все довольно хорошо. Оставил комментарии с тем, что можно улучшить и что нужно поправить, плюс пару вопросов)
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку)

2023-04-20 14:10 UTC, TarasovSam commented on src/main/resources/data.sql
> +INSERT INTO MPA (id, name) VALUES (1, 'G');
Для вставки одним запросом можно было бы использовать

merge into rating (rating_id, name)
values (1, 'G'),
(2, 'PG'),
(3, 'PG-13'),
(4, 'R'),
(5, 'NC-17');

Аналогично с жанрами)

2023-04-20 14:10 UTC, TarasovSam commented on src/main/resources/schema.sql
> +create table IF NOT EXISTS USERS
Можно было бы ввести ограничение на уникальность логина и почты на уровне таблицы в БД)

create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);

2023-04-20 14:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage {
Эта реализация более не будет использовать, ее можно исключить)

2023-04-20 14:10 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Эта реализация более не будет использовать, ее можно исключить)

2023-04-21 01:35 UTC, shumitum commented
Семён, привет!
Внес изменения в код с учётом твоих комментариев.
Спасибо за советы!

2023-04-21 10:16 UTC, TarasovSam reviewed
Вадим, привет!
Проверил твое задание, спасибо за работу. Оставил еще несколько комментариев с тем, что можно улучшить)
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-04-21 10:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull private int rate;
Погоди, под рейтингом я имел в виду Mpa, а не rate)
Rate - это грубо говоря каунтер (счетчик), поэтому аннотация для него не нужно (к тому же по условию есть дефолтное значение).

2023-04-21 10:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
Выше написать не могу)
Все же для работы с жанрами, рейтингами, лайками следует ввести другие DAO, так как это отдельные сущности в БД
Если будет возможность выдели в отдельные классы, дальше будет легче в работе с ними

2023-04-21 10:16 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
А тут не могу написать ниже))
Для работы с друзьями тоже лучше ввести еще один DAO, так как это отдельная сущность в БД

2023-04-23 03:15 UTC, merged